version: '3.1'

services:
  db:
    image: postgres
    container_name: dev_postgres
    restart: always
    env_file:
      - database.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: dev_adminer
    restart: always
    ports:
      - 8080:8080